name: VFS Monitor Scheduler
on:
  schedule:
    - cron: '*/5 * * * *'   # every 5 minutes
  workflow_dispatch:

jobs:
  run-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run VFS check
        env:
          MONITOR_CONFIG_JSON: ${{ secrets.MONITOR_CONFIG_JSON }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          # Add each monitor's credentials as environment secrets:
          VFS_USER_1: ${{ secrets.VFS_USER_1 }}
          VFS_PASS_1: ${{ secrets.VFS_PASS_1 }}
          # Add more VFS_USER_2, VFS_PASS_2 etc if you have them
        run: |
          node check.js
